apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-github-8dlu8qmbh76w2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-github-8dlu8qmbh76w2
    app.kubernetes.io/part-of: application-github-yg4p2zsg6kw4x
  name: component-github-8dlu8qmbh76w2
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-github-8dlu8qmbh76w2
status:
  loadBalancer: {}
